name: Deploy Admin Frontend to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub (or your container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: vochanhtin139/admin-frontend:latest

      # Step 4: Deploy to DigitalOcean Droplet via SSH
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          script: |
            # Pull the latest Docker image
            docker pull vochanhtin139/admin-frontend:latest

            # Stop and remove the existing container, if any
            docker stop admin-frontend || true
            docker rm admin-frontend || true

            # Run a new container
            docker run -d --name admin-frontend -p 81:81 vochanhtin139/admin-frontend:latest
